openapi: 3.0.0
info:
  title: Road Reports API
  version: 1.0.0
  description: API de gestion des signalements routiers avec Auth JWT (fallback offline), synchro Firebase ↔ Postgres, et gestion utilisateurs.
servers:
  - url: http://localhost/api
    description: Dev server

tags:
  - name: Auth
    description: Authentification JWT (online Firebase + fallback offline)
  - name: Sync
    description: Synchronisation Firebase ↔ Postgres
  - name: Users
    description: Gestion utilisateurs (déblocage, reset)
  - name: Reports
    description: Signalements routiers

paths:
  /auth/login:
    post:
      tags: [Auth]
      summary: Login (online Firebase, fallback offline si pas de réseau)
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/LoginRequest' }
      responses:
        '200':
          description: Token JWT (Firebase ou local)
          content:
            application/json:
              schema: { $ref: '#/components/schemas/AuthResponse' }
              examples:
                online:
                  summary: Succès online (Firebase)
                  value:
                    accessToken: eyJhbGciOiJSUzI1NiIsIn...
                    refreshToken: <firebaseRefresh>
                    mode: online
                offline:
                  summary: Succès offline (JWT local)
                  value:
                    accessToken: eyJhbGciOiJIUzI1NiIsIn...
                    refreshToken: null
                    mode: offline
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/ServerError' }

  /auth/refresh:
    post:
      tags: [Auth]
      summary: Rafraîchir le token (si mode online)
      security: [{ bearerAuth: [] }]
      responses:
        '200':
          description: Nouveau token
          content:
            application/json:
              schema: { $ref: '#/components/schemas/AuthResponse' }
        '401': { $ref: '#/components/responses/Unauthorized' }

  /auth/logout:
    post:
      tags: [Auth]
      summary: Invalider la session (online et/ou offline)
      security: [{ bearerAuth: [] }]
      responses:
        '200': { description: Déconnexion effectuée }

  /sync/push:
    post:
      tags: [Sync]
      summary: Pousser les données locales vers Firebase/Postgres
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/SyncPayload' }
      responses:
        '200': { description: Données synchronisées }
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }

  /sync/pull:
    get:
      tags: [Sync]
      summary: Récupérer les données distantes pour mise à jour locale
      security: [{ bearerAuth: [] }]
      responses:
        '200':
          description: Données récupérées
          content:
            application/json:
              schema:
                type: object
                properties:
                  reports:
                    type: array
                    items: { $ref: '#/components/schemas/Report' }
        '401': { $ref: '#/components/responses/Unauthorized' }

  /users/{userId}/unblock:
    post:
      tags: [Users]
      summary: Débloquer un utilisateur
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: userId
          required: true
          schema: { type: string }
      responses:
        '200': { description: Utilisateur débloqué }
        '404': { description: Utilisateur introuvable }
        '401': { $ref: '#/components/responses/Unauthorized' }

  /users/{userId}/reset-password:
    post:
      tags: [Users]
      summary: Réinitialiser le mot de passe (reset local + trigger Firebase si online)
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: userId
          required: true
          schema: { type: string }
      responses:
        '200': { description: Mot de passe réinitialisé (voir email ou token) }
        '404': { description: Utilisateur introuvable }

  /reports:
    get:
      tags: [Reports]
      summary: Lister les signalements
      security: [{ bearerAuth: [] }]
      responses:
        '200':
          description: Liste des signalements
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Report' }
    post:
      tags: [Reports]
      summary: Créer un signalement
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ReportCreate' }
      responses:
        '201':
          description: Signalement créé
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Report' }
        '400': { $ref: '#/components/responses/BadRequest' }

  /reports/{id}:
    get:
      tags: [Reports]
      summary: Détail d’un signalement
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Signalement
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Report' }
        '404': { description: Introuvable }
    put:
      tags: [Reports]
      summary: Mettre à jour un signalement
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ReportUpdate' }
      responses:
        '200': { description: Mis à jour }
        '404': { description: Introuvable }
    delete:
      tags: [Reports]
      summary: Supprimer un signalement
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '204': { description: Supprimé }
        '404': { description: Introuvable }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    BadRequest:
      description: Requête invalide
      content:
        application/json:
          schema:
            type: object
            properties:
              error: { type: string, example: "Invalid payload" }
    Unauthorized:
      description: Non autorisé (token manquant ou invalide)
      content:
        application/json:
          schema:
            type: object
            properties:
              error: { type: string, example: "Unauthorized" }
    ServerError:
      description: Erreur serveur
      content:
        application/json:
          schema:
            type: object
            properties:
              error: { type: string, example: "Internal server error" }

  schemas:
    User:
      type: object
      properties:
        id: { type: string }
        email: { type: string, format: email }
        role: { type: string, enum: [admin, moderator, user] }
        blocked: { type: boolean }
        createdAt: { type: string, format: date-time }
    Report:
      type: object
      properties:
        id: { type: string }
        userId: { type: string }
        latitude: { type: number, format: double }
        longitude: { type: number, format: double }
        status: { type: string, enum: [nouveau, en_cours, termine] }
        surface_m2: { type: number, format: double }
        budget: { type: number, format: double }
        createdAt: { type: string, format: date-time }
    ReportCreate:
      type: object
      required: [latitude, longitude, status]
      properties:
        latitude: { type: number, format: double, example: 48.8566 }
        longitude: { type: number, format: double, example: 2.3522 }
        status: { type: string, enum: [nouveau, en_cours, termine], example: nouveau }
        surface_m2: { type: number, format: double, example: 120.5 }
        budget: { type: number, format: double, example: 15000 }
    ReportUpdate:
      allOf:
        - $ref: '#/components/schemas/ReportCreate'
      required: []
    SyncPayload:
      type: object
      properties:
        lastSync: { type: string, format: date-time, example: "2026-02-02T12:00:00Z" }
        reports:
          type: array
          items: { $ref: '#/components/schemas/Report' }
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email: { type: string, format: email }
        password: { type: string, format: password }
    AuthResponse:
      type: object
      properties:
        accessToken: { type: string }
        refreshToken: { type: string, nullable: true }
        mode: { type: string, enum: [online, offline] }

security:
  - bearerAuth: []
